# Generated by Django 3.2.7 on 2021-09-23 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='rates',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.postsrates'),
        ),
    ]
